# Generated by Django 5.0.7 on 2024-07-29 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEnviado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_radicado', models.CharField(max_length=20, unique=True)),
                ('fecha_radicacion', models.DateField(auto_now_add=True)),
                ('asunto', models.CharField(max_length=100)),
                ('anexos', models.IntegerField()),
                ('nombre_destinatario', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(upload_to='pdfs/')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gesdoc_Sena.ciudad')),
                ('dependencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gesdoc_Sena.dependencia')),
                ('nombre_remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoRecibido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_radicado', models.CharField(max_length=20, unique=True)),
                ('fecha_recibido_documento', models.DateField(auto_now_add=True)),
                ('nombre_entidad_persona', models.CharField(max_length=255)),
                ('asunto', models.CharField(max_length=100)),
                ('radicado_origen', models.CharField(max_length=20)),
                ('contenido', models.TextField()),
                ('fecha_creacion_documento', models.DateField()),
                ('anexos', models.IntegerField()),
                ('archivo_pdf', models.FileField(upload_to='pdfs/')),
                ('correo_funcionario_destinatario', models.EmailField(max_length=254)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gesdoc_Sena.ciudad')),
                ('dependencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gesdoc_Sena.dependencia')),
                ('nombre_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_recibidos_asignados', to=settings.AUTH_USER_MODEL)),
                ('respuesta_radicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_recibidas', to='Gesdoc_Sena.documentoenviado')),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gesdoc_Sena.tipodocumento')),
            ],
        ),
        migrations.AddField(
            model_name='documentoenviado',
            name='respuesta_radicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_enviadas', to='Gesdoc_Sena.documentorecibido'),
        ),
        migrations.CreateModel(
            name='OtrosRadicados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_radicado', models.CharField(max_length=20, unique=True)),
                ('fecha_recibido', models.DateField(auto_now_add=True)),
                ('nombre_remitente', models.CharField(max_length=255)),
                ('radicado_origen', models.CharField(max_length=20)),
                ('anexos', models.IntegerField()),
                ('archivo_pdf', models.FileField(upload_to='pdfs/')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gesdoc_Sena.ciudad')),
                ('dependencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gesdoc_Sena.dependencia')),
                ('nombre_funcionario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otros_radicados', to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gesdoc_Sena.tipodocumento')),
            ],
            options={
                'verbose_name': 'Otro Radicado',
                'verbose_name_plural': 'Otros Radicados',
            },
        ),
        migrations.AddField(
            model_name='documentoenviado',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gesdoc_Sena.tipodocumento'),
        ),
    ]
