# Generated by Django 5.0.7 on 2024-07-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesdoc_Sena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoenviado',
            name='numero_radicado',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='documentorecibido',
            name='numero_radicado',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='otrosradicados',
            name='numero_radicado',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
