# Generated by Django 5.0.7 on 2024-07-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gesdoc_Sena', '0002_alter_documentoenviado_numero_radicado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
    ]
