# Generated by Django 5.0.7 on 2024-07-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gesdoc_Sena', '0003_alter_ciudad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otrosradicados',
            options={'verbose_name': 'Otro radicado', 'verbose_name_plural': 'Otros radicados'},
        ),
    ]
